name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use the appropriate Python version for your project

      # Install dependencies
    - name: Install dependencies
      working-directory: flask_app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      # Run tests with MongoDB credentials from secrets
      - name: Run tests
        env:
          MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        run: |
          pytest tests/ --disable-warnings
